name: Build Scripta Desktop

on: [push,workflow_dispatch]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-22.04, windows-2022]
        include:
          - environment: ubuntu-22.04
            publish-runtime-id: linux-x64
          - environment: windows-2022
            publish-runtime-id: win10-x64

    runs-on: ${{ matrix.environment }}

    steps:
    - name: Avoid git mutating files on checkout
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v2

    - name: Display Cargo version
      run: cargo  --version

    - name: install tauri
      run: cargo  install  tauri-cli

    - name: rustc  --print target-list
      run: rustc  --print target-list

    - name: build the app
      run: cargo  tauri  build  --verbose

    - name: Publish artifacts
      uses: actions/upload-artifact@v1
      with:
        name: scripta-desktop-${{github.sha}}-${{ matrix.publish-runtime-id }}
        path: ./publish
